import Link from 'next/link';
import { FileText, ArrowLeft } from 'lucide-react';

const C = { blue: '#1e40af', dark: '#1f2937', border: '#e5e7eb' };

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `By accessing or using Fabbrik ("the Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, you may not access or use the Service. These Terms constitute a legally binding agreement between you and Immortal Reality PA LLC ("Company", "we", "us", or "our").`,
  },
  {
    id: 'license',
    title: '2. License Grant',
    content: `Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your personal or internal business purposes. You may not sublicense, resell, or distribute the Service or any content generated by the Service without prior written consent. All blueprints, reports, and analyses generated by the Service are provided for your use only. You retain ownership of your input data, and we retain ownership of the Service, its algorithms, and underlying technology.`,
  },
  {
    id: 'responsibilities',
    title: '3. User Responsibilities',
    content: `You are responsible for: (a) maintaining the confidentiality of your account credentials; (b) all activities that occur under your account; (c) ensuring that your use of the Service complies with all applicable laws and regulations; (d) the accuracy and legality of the data you provide to the Service. You agree not to: (i) use the Service for any unlawful purpose; (ii) attempt to gain unauthorized access to any part of the Service; (iii) interfere with or disrupt the Service; (iv) reverse engineer, decompile, or disassemble the Service; (v) use automated tools to scrape or extract data from the Service.`,
  },
  {
    id: 'liability',
    title: '4. Limitation of Liability',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM: (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (C) ANY CONTENT OBTAINED FROM THE SERVICE; (D) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT. IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRIOR TO THE CLAIM.`,
  },
  {
    id: 'indemnification',
    title: '5. Indemnification',
    content: `You agree to defend, indemnify, and hold harmless the Company and its officers, directors, employees, contractors, agents, licensors, and suppliers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms or your use of the Service.`,
  },
  {
    id: 'governing-law',
    title: '6. Governing Law',
    content: `These Terms shall be governed by and construed in accordance with the laws of the Commonwealth of Pennsylvania, United States, without regard to its conflict of law provisions. Any legal action or proceeding arising under these Terms shall be brought exclusively in the federal or state courts located in Pennsylvania, and you consent to the personal jurisdiction and venue of such courts.`,
  },
  {
    id: 'changes',
    title: '7. Changes to Terms',
    content: `We reserve the right to modify or replace these Terms at any time at our sole discretion. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use the Service after those revisions become effective, you agree to be bound by the revised terms.`,
  },
  {
    id: 'contact',
    title: '8. Contact Information',
    content: `If you have any questions about these Terms, please contact us at: legal@fabbrik.us — Immortal Reality PA LLC.`,
  },
];

export default function Terms() {
  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: "'Inter', sans-serif" }}>
      <header className="sticky top-0 z-50 bg-white border-b" style={{ borderColor: C.border }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-16">
          <Link href="/" className="text-xl font-bold" style={{ color: C.blue }}>Fabbrik</Link>
          <Link href="/" className="flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Link>
        </div>
      </header>

      <section className="py-16 md:py-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto text-center">
          <FileText className="w-12 h-12 mx-auto mb-6" style={{ color: C.blue }} />
          <h1 className="text-4xl md:text-5xl font-bold mb-4" style={{ color: C.dark }}>Terms & Conditions</h1>
          <p className="text-lg text-gray-600">Last updated: April 1, 2026</p>
        </div>
      </section>

      <section className="px-4 sm:px-6 lg:px-8 pb-12">
        <div className="max-w-3xl mx-auto">
          <div className="bg-gray-50 rounded-lg border p-6" style={{ borderColor: C.border }}>
            <p className="font-semibold text-sm mb-3" style={{ color: C.dark }}>Table of Contents</p>
            <ul className="space-y-1.5">
              {SECTIONS.map(s => (
                <li key={s.id}>
                  <a href={`#${s.id}`} className="text-sm hover:underline transition-colors" style={{ color: C.blue }}>{s.title}</a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      <section className="px-4 sm:px-6 lg:px-8 pb-16">
        <div className="max-w-3xl mx-auto space-y-10">
          {SECTIONS.map(s => (
            <div key={s.id} id={s.id}>
              <h2 className="text-xl font-bold mb-3" style={{ color: C.dark }}>{s.title}</h2>
              <p className="text-sm text-gray-600 leading-relaxed whitespace-pre-line">{s.content}</p>
            </div>
          ))}
        </div>
      </section>

      <footer className="py-8 px-4 sm:px-6 lg:px-8 border-t" style={{ borderColor: C.border }}>
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row justify-between items-center text-xs text-gray-500">
          <p>© 2026 Fabbrik. Immortal Reality PA LLC. All rights reserved.</p>
          <div className="flex gap-4 mt-2 sm:mt-0">
            <Link href="/security" className="hover:text-gray-900 transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-gray-900 transition-colors">Terms</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
